networks:
 aurora-skyes:
  driver: bridge

services:
 postgres:
  image: postgres:17.2
  container_name: postgres_container
  environment:
  POSTGRES_USER: admin
  POSTGRES_PASSWORD: admin123
  POSTGRES_DB: aurora-skyes
  ports:
   - "5432:5432"
  volumes:
   - postgres_data:/var/lib/postgresql/data
  networks:
   - aurora-skyes

 pgadmin:
  image: dpage/pgadmin4:8.12
  container_name: pgadmin_container
  environment:
   PGADMIN_DEFAULT_EMAIL: admin@admin.com
   PGADMIN_DEFAULT_PASSWORD: admin
  ports:
   - "8000:80"
  networks:
   - aurora-skyes
  depends_on:
   - postgres

volumes:
 postgres_data:
  driver: local